# Generated by Django 5.0.2 on 2024-02-20 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
