# Generated by Django 5.0.2 on 2024-03-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_rename_profile_pic_profile_profilepicurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilePicUrl',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/image/'),
        ),
    ]
