# Generated by Django 5.0.2 on 2024-03-04 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_profile_profilepicurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profilePicUrl',
            new_name='image',
        ),
    ]
