version: '3.8'

services:
  db:
    container_name: db
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: myuser
      POSTGRES_DB: mydb
      POSTGRES_PASSWORD: postrgres
    env_file:
      - ./.env
    ports:
      - "5432:5432"


volumes:
  postgres_data:
