version: '3.8'

services:
  db:
    container_name: db
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: myuser
      POSTGRES_DB: mydb
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    networks: // Add the 'networks' section
      - mynetwork

  db_image: 
    image: mongo
    restart: always 
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    networks: // Add the 'networks' section
      - mynetwork

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks: // Add the 'networks' section
      - mynetwork

volumes:
  postgres_data:
